# Generated by Django 4.2 on 2023-04-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play_date',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
