# Generated by Django 4.2 on 2023-04-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='type',
            new_name='visit',
        ),
    ]
