# Generated by Django 4.2 on 2023-04-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_type_appointment_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Visit Date'),
        ),
        migrations.AddField(
            model_name='cat',
            name='play',
            field=models.ManyToManyField(to='main_app.play_date'),
        ),
    ]
